name: Daily Deploy Application Production

on: 
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with: 
                distribution: 'temurin' 
                java-version: '17'

            - name: Install Maven
              run: sudo apt-get install -y maven

            - name: Build Project
              run: mvn clean install -DskipTests

            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Build Docker Image
              run: docker build -t wladisilva/daily .

            - name: Push Image Docker
              run: docker push wladisilva/daily
    
    deploy:
      needs: build
      runs-on: self-hosted
      steps: 
        - name: Run Docker Container
          run: docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} -e DATABASE_URL=${{secrets.DATABASE_URL}} --name daily wladisilva/daily 

        - name: Pull Image From Docker Hub
          run: docker pull wladisilva/daily:latest

       
              
